### PR TITLE
Add support to smsapi-notifier

### PR DESCRIPTION
**Pull request by szepczynski**
Hi,

I created integration to notifier to support polish operators with smsapi.pl service.

smsapi-notifier is here: https://github.com/szepczynski/smsapi-notifier

I've tested integration by using this version of framework-bundle:
https://github.com/szepczynski/framework-bundle

and symfony-notifier in this PR

Can you add support of smsapi-notfier to symfony/symfony-notifier and symfony/framework-bundle?

### CODE REVIEW

**Comment by szepczynski** [comment]
Hi,

The symfony/symfony doesn't includes symfony/notifier component itself. It's only a dependency of symfony/symfony. In which way should I provide a PR to symfony/notifier?

**Comment by szepczynski** [comment]
Hi @nicolas-grekas,

The symfony/symfony doesn't includes symfony/notifier component itself. It's only exists as a dependency of symfony/symfony. In which way should I provide a PR to symfony/notifier?

I've created integration to notifier to support polish sms operator - smsapi.pl

Here is smsapi-notifier integration: https://github.com/szepczynski/smsapi-notifier
Here are changes in notifier repository including smsapi-notifier: https://github.com/szepczynski/notifier
Here are changes in framework-bundle repository including smsapi-notifier: https://github.com/szepczynski/framework-bundle
Could someone integrate this into notifier component?

**Comment by fabpot** [comment]
All the work is done in symfony/symfony, which is then split into several read-only repositories like this one.

**Comment by szepczynski** [comment]
Thanks for the reply; I click on Fork in symfony/symfony repo, but didn't notice that repo wasn't a fresh fork because I fork in the past. When I clone repo local I can't find on master Notifier component and I didn't know how to make a PR on symfony/symfony if this component does not exists :) 

Here is PR: https://github.com/symfony/symfony/pull/36940

**Pull request closed without merging**
